In [1]:
import pandas as pd
import numpy as np

In [75]:
health = pd.read_csv("India_health.csv")
imr = pd.read_excel("Infant_mortality_rate.xls",header=[2,3])
beds = pd.read_csv("Hospitals_and_beds.csv")
gsdp = pd.read_csv("gsdp_data.csv")
coords = pd.read_csv("state_coords.csv")

In [76]:
print("Health:",health.shape)
print("IMR:",imr.shape)
print("Beds:",beds.shape)
print("GSDP:",gsdp.shape)
print("Coords:",coords.shape)

Health: (37, 12)
IMR: (39, 14)
Beds: (43, 10)
GSDP: (29, 17)
Coords: (36, 4)

In [4]:
#health data cleaning
health.head()

,Sl.No.,State/UT,Proportion of men and women Reporting Asthma 15-49 years - Men,Proportion of men and women Reporting Asthma 15-49 years - Women,Percentage of Grade-II disability cases amongst new detected cases of Leprosy - 2015,Percentage of Grade-II disability cases amongst new detected cases of Leprosy - 2020 (Provisional),Percentage of population (15-24 years) with comprehensive knowledge of HIV/AIDS - Men,Percentage of population (15-24 years) with comprehensive knowledge of HIV/AIDS - Women,Prevalence of hypertension among men and women age 15-49 years - Men,Prevalence of hypertension among men and women age 15-49 years - Women,Percentage of men and women age 15-49 years with high Blood sugar level (>140 mg/dl) (%) - Men,Percentage of men and women age 15-49 years with high Blood sugar level (>140 mg/dl) (%) - Women
0,NaN,India,1.2,1.9,4.60,2.39,31.5,21.7,11.0,14.8,8.0,5.8
1,1.0,Andhra Pradesh,1.6,3.0,6.64,2.75,63.2,36.2,12.5,17.5,9.8,8.2
2,2.0,Assam,0.3,1.2,10.24,10.81,19.8,8.4,18.0,20.8,6.6,5.2
3,3.0,Bihar,0.7,0.9,3.60,2.76,24.7,10.0,8.2,11.0,6.7,4.1
4,4.0,Chattisgarh,1.4,1.8,7.24,3.41,35.3,22.3,10.0,13.2,9.7,5.7

In [15]:
health.isnull().sum()

State/UT                                                                                               0
Proportion of men and women Reporting Asthma 15-49 years - Men                                         0
Proportion of men and women Reporting Asthma 15-49 years - Women                                       0
Percentage of Grade-II disability cases amongst new detected cases of Leprosy - 2015                   0
Percentage of Grade-II disability cases amongst new detected cases of Leprosy - 2020 (Provisional)     0
Percentage of population (15-24 years) with comprehensive knowledge of HIV/AIDS - Men                  0
Percentage of population (15-24 years) with comprehensive knowledge of HIV/AIDS - Women                0
Prevalence of hypertension among men and women age 15-49 years  - Men                                  0
Prevalence of hypertension among men and women age 15-49 years  - Women                                0
Percentage of men and women age 15-49 years with high Blood sugar level (>140 mg/dl) (%)    - Men      0
Percentage of men and women age 15-49 years with high Blood sugar level (>140 mg/dl) (%)    - Women    0
dtype: int64

In [14]:
health.drop(columns=['Sl.No.'],inplace=True)

In [36]:
health.columns

Index(['State/UT',
       'Proportion of men and women Reporting Asthma 15-49 years - Men',
       'Proportion of men and women Reporting Asthma 15-49 years - Women',
       'Percentage of Grade-II disability cases amongst new detected cases of Leprosy - 2015',
       'Percentage of Grade-II disability cases amongst new detected cases of Leprosy - 2020 (Provisional)',
       'Percentage of population (15-24 years) with comprehensive knowledge of HIV/AIDS - Men',
       'Percentage of population (15-24 years) with comprehensive knowledge of HIV/AIDS - Women',
       'Prevalence of hypertension among men and women age 15-49 years  - Men',
       'Prevalence of hypertension among men and women age 15-49 years  - Women',
       'Percentage of men and women age 15-49 years with high Blood sugar level (>140 mg/dl) (%)    - Men',
       'Percentage of men and women age 15-49 years with high Blood sugar level (>140 mg/dl) (%)    - Women'],
      dtype='object')

In [37]:
health_clean = health.rename(columns={
    'State/UT': 'state',
    'Proportion of men and women Reporting Asthma 15-49 years - Men': 'asthma_men',
    'Proportion of men and women Reporting Asthma 15-49 years - Women': 'asthma_women',
    'Percentage of Grade-II disability cases amongst new detected cases of Leprosy - 2015': 'leprosy_2015',
    'Percentage of Grade-II disability cases amongst new detected cases of Leprosy - 2020 (Provisional)': 'leprosy_2020',
    'Percentage of population (15-24 years) with comprehensive knowledge of HIV/AIDS - Men': 'hiv_knowledge_men',
    'Percentage of population (15-24 years) with comprehensive knowledge of HIV/AIDS - Women': 'hiv_knowledge_women',
    'Prevalence of hypertension among men and women age 15-49 years  - Men': 'hypertension_men',
    'Prevalence of hypertension among men and women age 15-49 years  - Women': 'hypertension_women',
    'Percentage of men and women age 15-49 years with high Blood sugar level (>140 mg/dl) (%)    - Men': 'high_blood_sugar_men',
    'Percentage of men and women age 15-49 years with high Blood sugar level (>140 mg/dl) (%)    - Women': 'high_blood_sugar_women'
})

In [38]:
health_clean['state'] = health_clean['state'].astype(str).str.strip().str.title()

In [40]:
health_clean.head()

,state,asthma_men,asthma_women,leprosy_2015,leprosy_2020,hiv_knowledge_men,hiv_knowledge_women,hypertension_men,hypertension_women,high_blood_sugar_men,high_blood_sugar_women
0,India,1.2,1.9,4.60,2.39,31.5,21.7,11.0,14.8,8.0,5.8
1,Andhra Pradesh,1.6,3.0,6.64,2.75,63.2,36.2,12.5,17.5,9.8,8.2
2,Assam,0.3,1.2,10.24,10.81,19.8,8.4,18.0,20.8,6.6,5.2
3,Bihar,0.7,0.9,3.60,2.76,24.7,10.0,8.2,11.0,6.7,4.1
4,Chattisgarh,1.4,1.8,7.24,3.41,35.3,22.3,10.0,13.2,9.7,5.7

In [41]:
health_clean.shape

(37, 11)

In [42]:
health.isnull().sum()

State/UT                                                                                               0
Proportion of men and women Reporting Asthma 15-49 years - Men                                         0
Proportion of men and women Reporting Asthma 15-49 years - Women                                       0
Percentage of Grade-II disability cases amongst new detected cases of Leprosy - 2015                   0
Percentage of Grade-II disability cases amongst new detected cases of Leprosy - 2020 (Provisional)     0
Percentage of population (15-24 years) with comprehensive knowledge of HIV/AIDS - Men                  0
Percentage of population (15-24 years) with comprehensive knowledge of HIV/AIDS - Women                0
Prevalence of hypertension among men and women age 15-49 years  - Men                                  0
Prevalence of hypertension among men and women age 15-49 years  - Women                                0
Percentage of men and women age 15-49 years with high Blood sugar level (>140 mg/dl) (%)    - Men      0
Percentage of men and women age 15-49 years with high Blood sugar level (>140 mg/dl) (%)    - Women    0
dtype: int64

In [56]:
#imr data cleaning
imr.head()

,index,Sl.No._Unnamed: 0_level_1,States/Union Territorries_Unnamed: 1_level_1,1961_Male,1961_Female,1961_Person,2009_Male,2009_Female,2009_Person,2010_Male,2010_Female,2010_Person,2011_Male,2011_Female,2011_Person
0,0,1,2,3,4,5,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0
1,1,1,Kerala,55,48,52,10.0,13.0,12.0,13.0,14.0,13.0,11.0,13.0,12.0
2,2,2,Puducherry,77,68,73,25.0,20.0,22.0,22.0,22.0,22.0,17.0,20.0,19.0
3,3,3,Mizoram,73,65,69,33.0,38.0,36.0,36.0,39.0,37.0,31.0,37.0,34.0
4,4,4,Manipur,31,33,32,14.0,18.0,16.0,11.0,16.0,14.0,8.0,15.0,11.0

In [43]:
imr.isnull().sum()

index                                           0
Sl.No._Unnamed: 0_level_1                       1
States/Union Territorries_Unnamed: 1_level_1    2
1961_Male                                       2
1961_Female                                     2
1961_Person                                     2
2009_Male                                       2
2009_Female                                     2
2009_Person                                     2
2010_Male                                       2
2010_Female                                     2
2010_Person                                     2
2011_Male                                       2
2011_Female                                     2
2011_Person                                     2
dtype: int64

In [45]:
#Flatten column names
imr.columns = ['_'.join([str(i) for i in col]).strip() for col in imr.columns]
#Reset index
imr = imr.reset_index()
#Check columns
imr.columns

Index(['index', 'Sl.No._Unnamed: 0_level_1',
       'States/Union Territorries_Unnamed: 1_level_1', '1961_Male',
       '1961_Female', '1961_Person', '2009_Male', '2009_Female', '2009_Person',
       '2010_Male', '2010_Female', '2010_Person', '2011_Male', '2011_Female',
       '2011_Person'],
      dtype='object')

In [48]:
#Select required columns
imr_clean = imr[[ 'States/Union Territorries_Unnamed: 1_level_1', '1961_Male']].copy()

In [49]:
#Rename columns
imr_clean.columns = ['state', 'imr']

In [50]:
#Clean state names
imr_clean['state'] = imr_clean['state'].astype(str).str.strip().str.title()

In [51]:
#Remove invalid rows
imr_clean = imr_clean.dropna(subset=['state'])

In [52]:
#Reset index
imr_clean = imr_clean.reset_index(drop=True)

In [53]:
#check
imr_clean.head()

        state imr
0           2   3
1      Kerala  55
2  Puducherry  77
3     Mizoram  73
4     Manipur  31

In [54]:
imr_clean = imr_clean.drop(0)

In [57]:
imr_clean.head()

                       state imr
1                     Kerala  55
2                 Puducherry  77
3                    Mizoram  73
4                    Manipur  31
5  Andaman & Nicobar Islands  78

In [58]:
#beds data cleaning
beds.head()

,Srl no.,State / UT,Number of Hospitals,Unnamed: 3,Unnamed: 4,Unnamed: 5,Number of Beds,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,Govt.,Local Body,Others,Total,Govt.,Local Body,Others,Total
1,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10
2,1,Andhra Pradesh,8,0,0,8,365,0,0,365
3,2,Arunachal Pradesh,11,0,1,12,100,0,25,125
4,3,Assam,4,0,0,4,205,0,0,205

In [59]:
#remove top garbage rows
beds = beds.iloc[2:]

In [62]:
#Reset index
beds = beds.reset_index(drop=True)
beds.head()

,Srl no.,State / UT,Number of Hospitals,Unnamed: 3,Unnamed: 4,Unnamed: 5,Number of Beds,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,1,Andhra Pradesh,8,0,0,8,365,0,0,365
1,2,Arunachal Pradesh,11,0,1,12,100,0,25,125
2,3,Assam,4,0,0,4,205,0,0,205
3,4,Bihar,8,0,0,8,950,0,0,950
4,5,Chhattisgarh,7,0,8,15,370,0,470,840

In [68]:
#Rename columns manually
beds_clean = beds.iloc[:, [1, 5, 9]].copy()
beds_clean.columns = ['state', 'hospitals', 'beds']

In [69]:
#Clean state names
beds_clean['state'] = beds_clean['state'].astype(str).str.strip().str.title()

In [70]:
#Convert to numbers
beds_clean['hospitals'] = pd.to_numeric(beds_clean['hospitals'], errors='coerce')
beds_clean['beds'] = pd.to_numeric(beds_clean['beds'], errors='coerce')

In [71]:
#Remove invalid rows
beds_clean = beds_clean.dropna(subset=['state'])
beds_clean = beds_clean.reset_index(drop=True)

In [72]:
beds_clean.head()

               state  hospitals   beds
0     Andhra Pradesh        8.0  365.0
1  Arunachal Pradesh       12.0  125.0
2              Assam        4.0  205.0
3              Bihar        8.0  950.0
4       Chhattisgarh       15.0  840.0

In [73]:
#GSDP Data Cleaning

,Sl. No.,Level of Education - State,Primary - 2012-2013,Primary - 2014-2015,Primary - 2014-2015.1,Upper Primary - 2012-2013,Upper Primary - 2013-2014,Upper Primary - 2014-2015,Secondary - 2012-2013,Secondary - 2013-2014,Secondary - 2014-2015,Senior Secondary - 2012-2013,Senior Secondary - 2013-2014,Senior Secondary - 2014-2015
0,1,A & N Islands,0.68,1.21,0.51,1.23,0.51,1.69,5.56,7.20,9.87,14.14,15.87,16.93
1,2,Andhra Pradesh,3.18,4.35,6.72,3.36,3.78,5.20,12.72,12.65,15.71,0.35,11.79,NaN
2,3,Arunachal Pradesh,15.16,10.89,10.82,7.47,5.59,6.71,12.93,14.49,17.11,5.11,17.07,18.42
3,4,Assam,6.24,7.44,15.36,7.20,7.05,10.51,26.77,30.43,27.06,4.69,7.24,NaN
4,5,Bihar,NaN,2.09,NaN,NaN,2.98,4.08,30.14,25.33,25.90,NaN,NaN,NaN

In [77]:
#GSDP Data Cleaning
gsdp.head()

,State Name,Geometry,NSDP Per Capita (Nominal)1996-97,NSDP Per Capita (Nominal)2000-01,NSDP Per Capita (Nominal)2005-06,NSDP Per Capita (Nominal)2010-11,NSDP Per Capita (Nominal)2011-12,NSDP Per Capita (Nominal)2012-13,NSDP Per Capita (Nominal)2013-14,NSDP Per Capita (Nominal)2014-15,NSDP Per Capita (Nominal)2015-16,NSDP Per Capita (Nominal)2016-17,NSDP Per Capita (Nominal)2017-18,NSDP Per Capita (Nominal)2018-19,NSDP Per Capita (Nominal)2019-20,Growth from 2000 to 2010,Growth from 2010 to 2019
0,Arunachal Pradesh,"POLYGON ((96.16260946675357 29.38078474502004,...","₹ 10,816","₹ 15,260","₹ 28,171","₹ 60,961","₹ 73,068","₹ 81,353","₹ 91,809","₹ 1,10,929","₹ 1,12,046","₹ 1,17,344","₹ 1,30,197","₹ 1,39,588","₹ 1,69,742",299%,178.0 %
1,Assam,MULTIPOLYGON (((89.74322932956994 26.303620341...,"₹ 7,394","₹ 12,803","₹ 18,396","₹ 33,087","₹ 41,142","₹ 44,599","₹ 49,734","₹ 52,895","₹ 60,817","₹ 66,330","₹ 74,184","₹ 82,078","₹ 86,801",158%,162.0 %
2,Bihar,MULTIPOLYGON (((84.50719832504274 24.263231032...,"₹ 4,001","₹ 6,415","₹ 8,223","₹ 19,111","₹ 21,750","₹ 24,487","₹ 26,948","₹ 28,671","₹ 30,404","₹ 34,156","₹ 38,631","₹ 43,822","₹ 46,292",197%,142.0 %
3,Chhattisgarh,"POLYGON ((83.33531747931829 24.09885072448139,...","₹ 8,353","₹ 10,744","₹ 20,117","₹ 41,165","₹ 55,177","₹ 60,849","₹ 69,880","₹ 72,936","₹ 73,590","₹ 81,808","₹ 89,813","₹ 96,887","₹ 1,04,989",283%,155.0 %
4,Goa,MULTIPOLYGON (((74.11917887850251 14.753440750...,"₹ 26,418","₹ 43,735","₹ 84,721","₹ 1,68,024","₹ 2,59,444","₹ 2,34,354","₹ 2,15,776","₹ 2,89,185","₹ 3,34,575","₹ 3,82,140","₹ 4,22,155","₹ 4,58,304","₹ 4,35,959",284%,159.0 %

In [78]:
#Select required columns
gsdp_clean = gsdp[['State Name', 'NSDP Per Capita (Nominal)2019-20']].copy()

In [79]:
#Rename columns
gsdp_clean.columns = ['state', 'gsdp']

In [80]:
#Remove ₹ and commas
gsdp_clean['gsdp'] = (gsdp_clean['gsdp'].astype(str).str.replace('₹', '').str.replace(',', ''))

In [81]:
#Convert to numeric
gsdp_clean['gsdp'] = pd.to_numeric(gsdp_clean['gsdp'], errors='coerce')

In [82]:
#Clean state names
gsdp_clean['state'] = gsdp_clean['state'].astype(str).str.strip().str.title()

In [83]:
#Remove null rows
gsdp_clean = gsdp_clean.dropna(subset=['state', 'gsdp'])
gsdp_clean = gsdp_clean.reset_index(drop=True)

In [84]:
#Check
gsdp_clean.head()

               state    gsdp
0  Arunachal Pradesh  169742
1              Assam   86801
2              Bihar   46292
3       Chhattisgarh  104989
4                Goa  435959

In [85]:
#Coords Data Cleaning
coords.head()

               state    capital  latitude  longitude
0     Andhra Pradesh  Amaravati   16.5062    80.6480
1  Arunachal Pradesh   Itanagar   27.0844    93.6053
2              Assam     Dispur   26.1433    91.7898
3              Bihar      Patna   25.5941    85.1376
4       Chhattisgarh     Raipur   21.2514    81.6296

In [86]:
#required columns
coords_clean = coords[['state', 'latitude', 'longitude']].copy()

In [87]:
#Standardize state names
coords_clean['state'] = coords_clean['state'].astype(str).str.strip().str.title()

In [88]:
#Ensure numeric values
coords_clean['latitude'] = pd.to_numeric(coords_clean['latitude'], errors='coerce')
coords_clean['longitude'] = pd.to_numeric(coords_clean['longitude'], errors='coerce')

In [89]:
#Check
coords_clean.head()

               state  latitude  longitude
0     Andhra Pradesh   16.5062    80.6480
1  Arunachal Pradesh   27.0844    93.6053
2              Assam   26.1433    91.7898
3              Bihar   25.5941    85.1376
4       Chhattisgarh   21.2514    81.6296

In [90]:
print("All files Data cleaned Successfully")

All files Data cleaned Successfully

In [91]:
print("IMR:", imr_clean.shape)
print("Beds:", beds_clean.shape)
print("GSDP:", gsdp_clean.shape)
print("Coords:", coords_clean.shape)

IMR: (38, 2)
Beds: (41, 3)
GSDP: (29, 2)
Coords: (36, 3)

In [105]:
#Common state name fixes
state_fix = {
    'Andaman And Nicobar Islands': 'Andaman & Nicobar Islands',
    'Dadra And Nagar Haveli And Daman And Diu': 'Dadra & Nagar Haveli And Daman & Diu',
    'Nct Of Delhi': 'Delhi',
    'A & N Islands': 'Andaman & Nicobar Islands'
}

for df in [imr_clean, beds_clean, gsdp_clean, coords_clean]:
    df['state'] = df['state'].replace(state_fix)

In [93]:
#Merge datasets
master = imr_clean.merge(beds_clean, on='state', how='left') \
                  .merge(gsdp_clean, on='state', how='left') \
                  .merge(coords_clean, on='state', how='left')

In [95]:
master.head()

,state,imr,hospitals,beds,gsdp,latitude,longitude
0,Kerala,55,162.0,4054.0,221904.0,8.5241,76.9366
1,Puducherry,77,0.0,0.0,NaN,11.9416,79.8083
2,Mizoram,73,2.0,100.0,187327.0,23.7271,92.7176
3,Manipur,31,10.0,0.0,84746.0,24.8170,93.9368
4,Andaman & Nicobar Islands,78,5.0,90.0,NaN,11.6234,92.7265

In [96]:
master.shape

(44, 7)

In [97]:
#Check missing values
master.isnull().sum()

state         0
imr           8
hospitals     9
beds          9
gsdp         18
latitude     13
longitude    13
dtype: int64

In [98]:
#Fill missing numeric values
master['hospitals'] = master['hospitals'].fillna(0)
master['beds'] = master['beds'].fillna(0)
master['gsdp'] = master['gsdp'].fillna(master['gsdp'].median())

In [103]:
master[master['latitude'].isnull()][['state']]

                   state
9        Jammu & Kashmir
19  Dadra & Nagar Haveli
31           Daman & Diu
32           Chhatisgarh
36                   Nan
37                   Nan
38                   Nan
39                   Nan
40                   Nan
41                   Nan
42                   Nan
43                   Nan

In [101]:
#Remove invalid rows
master = master.dropna(subset=['state'])
master = master[master['state'] != 'All India']

In [106]:
#Fix state name mismatch
state_fix = {
    'Jammu & Kashmir': 'Jammu And Kashmir',
    'Dadra & Nagar Haveli': 'Dadra And Nagar Haveli And Daman And Diu',
    'Daman & Diu': 'Dadra And Nagar Haveli And Daman And Diu',
    'Chhatisgarh': 'Chhattisgarh'
}

master['state'] = master['state'].replace(state_fix)
coords_clean['state'] = coords_clean['state'].replace(state_fix)

In [107]:
#Merge coordinates again
master = master.drop(columns=['latitude', 'longitude'], errors='ignore')

master = master.merge(coords_clean[['state', 'latitude', 'longitude']],on='state',how='left')

In [108]:
master[master['latitude'].isnull()][['state']]

                                       state
19  Dadra And Nagar Haveli And Daman And Diu
31  Dadra And Nagar Haveli And Daman And Diu
35                                       Nan
36                                       Nan
37                                       Nan
38                                       Nan
39                                       Nan
40                                       Nan
41                                       Nan
42                                       Nan

In [109]:
master.loc[
    master['state'] == 'Dadra And Nagar Haveli And Daman And Diu',
    ['latitude', 'longitude']
] = [20.3974, 72.8328]

In [110]:
master.isnull().sum()

state        0
imr          8
hospitals    0
beds         0
gsdp         0
latitude     8
longitude    8
dtype: int64

In [111]:
#Check which states are missing
master[master['imr'].isnull()][['state']]

   state
35   Nan
36   Nan
37   Nan
38   Nan
39   Nan
40   Nan
41   Nan
42   Nan

In [120]:
master[master['latitude'].isnull()][['state']]

   state
35   Nan
36   Nan
37   Nan
38   Nan
39   Nan
40   Nan
41   Nan
42   Nan

In [125]:
master['state'] = master['state'].astype(str).str.strip()

master = master[
    (master['state'].str.lower() != 'nan') &
    (master['state'] != '')
].reset_index(drop=True)

In [126]:
master.isnull().sum()

state        0
imr          0
hospitals    0
beds         0
gsdp         0
latitude     0
longitude    0
dtype: int64

In [127]:
print("Files Merged Successfully")

Files Merged Successfully

In [128]:
master.to_csv("health_master_final.csv", index=False)